[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
remappings = [
  "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
  "@chainlink/contracts=lib/chainlink-brownie-contracts/contracts/src/v0.8",
  "foundry-devops=lib/foundry-devops/src",
]
via-ir = true
fs_permissions = [
  { access = "read", path = "./functions" },
  { access = "read", path = "./broadcast" },
  { access = "read", path = "./reports" },
]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 2
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
